version: "2"

services:

  api:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=docker_dev
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.3-alpine
